// <auto-generated />
using System;
using EventManger.Infrastructure.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventManger.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApplicationUserEvent", b =>
                {
                    b.Property<Guid>("AttendedEventsEventID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttendeesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AttendedEventsEventID", "AttendeesId");

                    b.HasIndex("AttendeesId");

                    b.ToTable("ApplicationUserEvent");
                });

            modelBuilder.Entity("EventManger.Core.Domain.Entites.BlogPost", b =>
                {
                    b.Property<Guid>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimePosted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BlogId");

                    b.ToTable("blogPosts");
                });

            modelBuilder.Entity("EventManger.Core.Domain.Entites.Comment", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BlogPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CommentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommentatorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeCommented")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BlogPostId");

                    b.HasIndex("CommentId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("EventManger.Core.Domain.Entites.Event", b =>
                {
                    b.Property<Guid>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OrganizationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RoomID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.HasKey("EventID");

                    b.ToTable("Events", (string)null);

                    b.HasData(
                        new
                        {
                            EventID = new Guid("9a097ff1-5b39-4325-8818-5dc75b20e948"),
                            Description = "Annual technology conference.",
                            EndTime = new DateTime(2025, 6, 5, 22, 35, 12, 225, DateTimeKind.Local).AddTicks(6099),
                            Name = "Tech Conference 2023",
                            OrganizationID = new Guid("cee01121-1a9b-404d-b632-23f4e12985b9"),
                            PhotoUrl = "\\events-photos\\58147433-411f-47bc-88bb-c70b7ff2e68d.jpeg",
                            RoomID = new Guid("61e7f38c-9fdd-4836-8d31-2253c9ec7a49"),
                            StartTime = new DateTime(2025, 6, 4, 22, 35, 12, 225, DateTimeKind.Local).AddTicks(6073),
                            Status = 0,
                            Views = 0
                        },
                        new
                        {
                            EventID = new Guid("43d2b0aa-6e63-4ce0-aa43-f68dd4f744a8"),
                            Description = "Monthly team meeting.",
                            EndTime = new DateTime(2025, 5, 30, 0, 35, 12, 225, DateTimeKind.Local).AddTicks(6112),
                            Name = "Team Meeting",
                            OrganizationID = new Guid("1f627b5c-7ad1-4630-b2f5-aa09feb5e4a3"),
                            PhotoUrl = "\\events-photos\\4f289cfc-708c-4e78-b721-240be036d302.jpeg",
                            RoomID = new Guid("71571407-8325-4d99-b2c4-1922c9b552b0"),
                            StartTime = new DateTime(2025, 5, 29, 22, 35, 12, 225, DateTimeKind.Local).AddTicks(6111),
                            Status = 0,
                            Views = 0
                        },
                        new
                        {
                            EventID = new Guid("3c43b83d-e31d-4bb1-ae66-bf82c44826bf"),
                            Description = "A competition to solve real-world problems.",
                            EndTime = new DateTime(2025, 6, 12, 1, 35, 12, 225, DateTimeKind.Local).AddTicks(6117),
                            Name = "Problem Solving Competition",
                            OrganizationID = new Guid("8d68f10d-7cfe-43a6-a49d-406685b0ea0a"),
                            PhotoUrl = "\\events-photos\\69f744c9-6ce8-4802-bf62-83b92e22babc.jpeg",
                            RoomID = new Guid("61e7f38c-9fdd-4836-8d31-2253c9ec7a49"),
                            StartTime = new DateTime(2025, 6, 11, 22, 35, 12, 225, DateTimeKind.Local).AddTicks(6117),
                            Status = 0,
                            Views = 0
                        });
                });

            modelBuilder.Entity("EventManger.Core.Domain.Entites.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("EventManger.Core.Domain.Entites.NewsArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("NewsArticles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b73c14e0-c5d6-4802-bf5e-2b9fb4b50f03"),
                            Content = "<p><strong>Exciting news!</strong> The annual Tech Conference will be held on June 04, 2025.</p><p>This year's conference will feature <em>cutting-edge</em> presentations on AI, blockchain, and quantum computing.</p>",
                            CreatedDate = new DateTime(2025, 5, 23, 22, 35, 12, 225, DateTimeKind.Local).AddTicks(6276),
                            PhotoUrl = "\\news-photos\\74pCXBPyfCvb7HWEdm57HE.jpg",
                            Title = "Tech Conference 2023 Announced",
                            UpdatedDate = new DateTime(2025, 5, 27, 22, 35, 12, 225, DateTimeKind.Local).AddTicks(6278)
                        },
                        new
                        {
                            Id = new Guid("431ae806-2e14-4317-8e1f-61e453223552"),
                            Content = "<p>The university has partnered with <strong>Tech Innovators</strong> to establish a new research center.</p><p><em>\"This collaboration will accelerate innovation\"</em>, said the dean of the Technology college.</p>",
                            CreatedDate = new DateTime(2025, 5, 18, 22, 35, 12, 225, DateTimeKind.Local).AddTicks(6284),
                            PhotoUrl = "\\news-photos\\How-to-Build-Strategic-Partnerships-that-Boost-Sales-1.jpg",
                            Title = "New Research Partnership Formed"
                        },
                        new
                        {
                            Id = new Guid("f13305df-25f2-4a9f-a786-a97f805c7407"),
                            Content = "<p>The administration has announced plans for a <strong>$20 million</strong> renovation of the main campus buildings.</p><p>Construction is expected to begin in July.</p>",
                            CreatedDate = new DateTime(2025, 5, 25, 22, 35, 12, 225, DateTimeKind.Local).AddTicks(6389),
                            PhotoUrl = "\\news-photos\\BGU-NORTH-CAMPUS-02.jpg",
                            Title = "Campus Renovation Plans Unveiled",
                            UpdatedDate = new DateTime(2025, 5, 26, 22, 35, 12, 225, DateTimeKind.Local).AddTicks(6390)
                        },
                        new
                        {
                            Id = new Guid("429285e5-5729-41a3-84f4-6c0198043392"),
                            Content = "<p><em>Congratulations</em> to our computer science students for winning first place in the national coding competition!</p><p>The team developed an innovative <strong>AI-powered</strong> healthcare solution.</p>",
                            CreatedDate = new DateTime(2025, 5, 27, 22, 35, 12, 225, DateTimeKind.Local).AddTicks(6393),
                            PhotoUrl = "\\news-photos\\1716833964113.jpg",
                            Title = "Student Team Wins National Competition"
                        });
                });

            modelBuilder.Entity("EventManger.Core.Domain.Entites.Room", b =>
                {
                    b.Property<Guid>("RoomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.HasKey("RoomID");

                    b.ToTable("rooms");

                    b.HasData(
                        new
                        {
                            RoomID = new Guid("61e7f38c-9fdd-4836-8d31-2253c9ec7a49"),
                            Description = "A large conference room with 50 seats.",
                            Name = "Conference Room A",
                            Seats = 50
                        },
                        new
                        {
                            RoomID = new Guid("71571407-8325-4d99-b2c4-1922c9b552b0"),
                            Description = "A small meeting room with 10 seats.",
                            Name = "Meeting Room B",
                            Seats = 10
                        });
                });

            modelBuilder.Entity("EventManger.Core.Domain.Entities.Organization", b =>
                {
                    b.Property<Guid>("OrganizationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("College")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrganizationID");

                    b.ToTable("Organizations", (string)null);

                    b.HasData(
                        new
                        {
                            OrganizationID = new Guid("cee01121-1a9b-404d-b632-23f4e12985b9"),
                            College = "Technology",
                            Description = "A leading technology innovation company.",
                            Email = "contact@techinnovators.com",
                            LogoUrl = "\\logos\\3a75a9ba-1079-4854-92c9-a17f064e54af.jpg",
                            Name = "Tech Innovators"
                        },
                        new
                        {
                            OrganizationID = new Guid("1f627b5c-7ad1-4630-b2f5-aa09feb5e4a3"),
                            College = "Medicine",
                            Description = "Providing healthcare solutions worldwide.",
                            Email = "info@healthsolutions.com",
                            LogoUrl = "\\logos\\0ce4ea06-ddf0-4b94-b3f1-e37b5e63ae3a.jpg",
                            Name = "Health Solutions"
                        },
                        new
                        {
                            OrganizationID = new Guid("8d68f10d-7cfe-43a6-a49d-406685b0ea0a"),
                            College = "Engineering",
                            Description = "Institute of Electrical and Electronics Engineers.",
                            Email = "IEEE@gmail.com",
                            LogoUrl = "\\logos\\4b210b7b-3a14-43fd-af40-752431129fb0.png",
                            Name = "IEEE"
                        });
                });

            modelBuilder.Entity("EventManger.Core.Domain.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("45eded88-eaff-4dd7-8b4e-873f88c39ea2"),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("6b1e722c-0e06-4365-854d-112a34f7eb96"),
                            Name = "Attendee",
                            NormalizedName = "ATTENDEE"
                        },
                        new
                        {
                            Id = new Guid("cfa3e7d7-dba9-472d-a964-284b842a8280"),
                            Name = "Guest",
                            NormalizedName = "GUEST"
                        });
                });

            modelBuilder.Entity("EventManger.Core.Domain.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("BlogPostBlogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("BlogPostBlogId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7903876c-ada5-4e91-b9e3-a6682005d4b7"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dd870a8a-ed1f-46d5-889b-82573bf850e9",
                            Email = "admin@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEERsphduIQwSiBfNYU/u7NGqyyUlRVR68Xdcm2+XHi5aQDDiGg3wzUIT/1aWEnXWtg==",
                            PersonName = "admin",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5e2ebdd7-1db0-436f-bc37-40746c1f5577",
                            TwoFactorEnabled = false,
                            UserName = "admin@example.com"
                        },
                        new
                        {
                            Id = new Guid("d1055d57-7f97-4c75-945e-46101906aa6e"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fe131c40-d54b-4fe1-8b51-798478679e5b",
                            Email = "user1@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER1@EXAMPLE.COM",
                            NormalizedUserName = "USER1@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBmyc7407ZYCefLg9318FId7NWEXPwR3YZu0h7vMmwsESZcCkp85BrxuLIwbrglNdg==",
                            PersonName = "user1",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "61660e59-aeac-4ef1-97f8-095ef2f24fd0",
                            TwoFactorEnabled = false,
                            UserName = "user1@example.com"
                        },
                        new
                        {
                            Id = new Guid("a30856d8-e5ae-4acb-a6ba-069f6e6af117"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7437a040-400b-4bed-a3fc-39ab832311f5",
                            Email = "user2@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER2@EXAMPLE.COM",
                            NormalizedUserName = "USER2@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEO4jOjeYXgHf/TVXCVnmQp6irsplcfXTsvnavluQ4j15UWgfhX28H/zfGLz7SGR+BA==",
                            PersonName = "user2",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ebffa888-2a46-42d6-962c-f381b0d98420",
                            TwoFactorEnabled = false,
                            UserName = "user2@example.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("7903876c-ada5-4e91-b9e3-a6682005d4b7"),
                            RoleId = new Guid("45eded88-eaff-4dd7-8b4e-873f88c39ea2")
                        },
                        new
                        {
                            UserId = new Guid("d1055d57-7f97-4c75-945e-46101906aa6e"),
                            RoleId = new Guid("6b1e722c-0e06-4365-854d-112a34f7eb96")
                        },
                        new
                        {
                            UserId = new Guid("a30856d8-e5ae-4acb-a6ba-069f6e6af117"),
                            RoleId = new Guid("6b1e722c-0e06-4365-854d-112a34f7eb96")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ApplicationUserEvent", b =>
                {
                    b.HasOne("EventManger.Core.Domain.Entites.Event", null)
                        .WithMany()
                        .HasForeignKey("AttendedEventsEventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventManger.Core.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("AttendeesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventManger.Core.Domain.Entites.Comment", b =>
                {
                    b.HasOne("EventManger.Core.Domain.Entites.BlogPost", "BlogPost")
                        .WithMany("Comments")
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventManger.Core.Domain.Entites.Comment", null)
                        .WithMany("Replies")
                        .HasForeignKey("CommentId");

                    b.Navigation("BlogPost");
                });

            modelBuilder.Entity("EventManger.Core.Domain.Entites.Message", b =>
                {
                    b.HasOne("EventManger.Core.Domain.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventManger.Core.Domain.Identity.ApplicationUser", b =>
                {
                    b.HasOne("EventManger.Core.Domain.Entites.BlogPost", null)
                        .WithMany("Likes")
                        .HasForeignKey("BlogPostBlogId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("EventManger.Core.Domain.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("EventManger.Core.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("EventManger.Core.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("EventManger.Core.Domain.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventManger.Core.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("EventManger.Core.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventManger.Core.Domain.Entites.BlogPost", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("EventManger.Core.Domain.Entites.Comment", b =>
                {
                    b.Navigation("Replies");
                });
#pragma warning restore 612, 618
        }
    }
}
